before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: k6F0HE48CTxJT+kqj6bWAx25UJXifZSpAuNd56QaTfyXTHtmSbKEvmosWopvuhUUVTjfeBJ8SBl1gaq5s8yysmkXB4drgQZC032L9FSKa535YogQM/AmooXJ1Oc5t3m4nYRvWCoCQ7BTZuOSrm416A9atdHbgH6RN1VVx/m7Ku9Tt4pkVMyZTgP75d8fC5VwM1CJnsC6D/r3rYo2FOU5O0C6PFOlqVwwCPpF2DEiZf2QRitMz3nLBHbtGKvvoEVf6jCWQQmMjmeZ/5bOt/IXlhBkNOcd4O3qZmg6B/ihyImLRvipFeLQDTZ84E5fIev5bYYMZqETCQCF/79eG3QSveikQ+rdIujofd3U4gw37pWjc5OTZEqbrwmqbxy+REYG0rdmx0byxBN3mGwWZG4zzv+xMheqVylyRUwZVCye7lxCeduhxgYL+iWggVbg3iSuliTBLBULM22ji2y06XLYOVAkqPBU/PxCNLiV1YAkEkYk8cX9v16xFERPpR/R9Ol6sM6xqlaqhuGi3i5gp5GbMMKbzyCNUQ/j1xgGzJQcNzUFPCmahs6MBff0g4YtpJKToMWPT+g7vgG1C1NLFpkfcbI2ljNgEYqdkBiy4wNgNLXQjZ/8fqb+ZxXHqLOuDeMLfrVPnbOAQbkAzPtwOheSGsf3Cl6GKfpNNVBK9eI+fL8= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
